name: course_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  image_picker: ^0.8.7+5
  sqflite: ^2.2.8+2
  path_provider: ^2.0.15
  intl: ^0.17.0
  url_launcher: ^6.1.11
  flutter_rating_bar: ^4.0.1
  numberpicker: ^2.1.2
  panara_dialogs: ^0.1.4
  awesome_dialog: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
